- name: Update prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Update Alerts Configuration
  ansible.builtin.template:
    src: "{{ item }}".yml
    dest: /opt/prometheus/"{{ item }}".yml
  loop: 
    - service-down-alerts.yml
    - alerts.yml
       


- name: Restart prometheus
  ansible.builtin.systemd:
   name: prometheus
   state: restarted

